---
- name: install epel-release
  dnf: 
   name: 
    - epel-release
   state: present

- name: upgrade All Packages
  dnf:
    name: "*"
    state: latest

- name: install Java 11
  dnf: 
   name: 
    - vim
    - bash-completion
    - tmux
    - tree
    - htop
    - wget
    - unzip
    - curl
    - git
   state: present
